### ISSUE TITLE
openJDK Platform binary process runs forever

### ISSUE THREAD

**Issue by kozyakin** [valentjn/languagetool-languageserver#117]
**Describe the bug**
After executing ltex-cli.bat on any tex-file the process **_openJDK Platform binary (=java.exe)_**, which occupies about 800 MB, remains in RAM of Windows 10.

**Steps to reproduce**

1. Run the command

`ltex-cli.bat <tex file name>`

2. After finishing this command, inspect the running processes by Task Manager
3. Will be seen that the process **_openJDK Platform binary_**, which occupies about 800 MB, still running in background.

**Expected behavior**
 The process **_openJDK Platform binary (=java.exe)_** should be stopped after executing `ltex-cli.bat <tex file name>`

**LTeX configuration**
Default

**Version information**

- Operating system: Windows 10 21H1
- ltex-ls: 15.0.0
- Java: Microsoft openJDK 17

**Additional context/information**
The problem may be solved by manual "killing" java, say, by insetring in the end of `ltex-cli.bat` the string

`taskkill /f /im java.exe > nul`

but this is definitely not the good solution since this string kills ALL the instances of running java.exe.

**Comment by valentjn** [comment]
I can't reproduce this. As far as I understand, `ltex-cli.bat` finishes (i.e., the `cmd` prompt `C:\...>` is displayed again), but `java.exe` continues to run. I don't see any Java processes on my system after running `ltex-cli.bat`.

Can you please open a second `cmd` window and run `wmic process where "name like 'java.exe'" get processid,commandline` three times:
- once before the execution of `ltex-cli.bat`,
- once during the execution of `ltex-cli.bat` (`cmd` prompt is not yet visible),
- once after the execution of `ltex-cli.bat` (`cmd` prompt is visible again),

and post the three outputs?

**Comment by kozyakin** [comment]
Please find attached files "before", "during" and "after" of outputs of the command **wmic process where "name like '%java%'"** which you requested (before execution, during and after).

I also attached related screenshots of Task Manage
[before.txt](https://github.com/valentjn/ltex-ls/files/7459624/before.txt)
[during.txt](https://github.com/valentjn/ltex-ls/files/7459627/during.txt)
[after.txt](https://github.com/valentjn/ltex-ls/files/7459632/after.txt)
![Screenshot 2021-11-02 123259](https://user-images.githubusercontent.com/57475371/139825367-98a78fb1-a4e8-4929-9026-a06c8c4bdad0.png)
![Screenshot 2021-11-02 123415](https://user-images.githubusercontent.com/57475371/139825386-cbb60a64-0c12-478d-b34c-34995bb773a9.png)

**Comment by valentjn** [comment]
Thanks for the info. Looks like the Java process for `ltex-ls` is not properly terminated by the Java process for `lsp-cli`.

I still can't reproduce this, even on another machine, and with the Microsoft build of OpenJDK. But I made `lsp-cli` terminate `ltex-ls` more aggressively, see commits above. Can you please test the [pre-release 15.0.1-alpha.2](https://github.com/valentjn/ltex-ls/releases/tag/15.0.1-alpha.2) to see if the issue is resolved there (see [docs on testing pre-releases](https://valentjn.github.io/ltex/ltex-ls/contributing.html#how-to-test-pre-releases))?

**Comment by kozyakin** [comment]
Now, all is running as expected: no **openJDK Platform binary** process after `ltex-cli.bat` finished!

Well done! Great! Thanks a lot!
