### ISSUE TITLE
support for ConTeXt markup

### ISSUE THREAD

**Issue by gour** [valentjn/languagetool-languageserver#120]
Hello,

how hard/easy would be to add support for [ConTeXt](https://wiki.contextgarden.net/Main_Page) markup which is quite nice alternative for `LaTeX`?

I'm aware that there is one [extension](https://wiki.contextgarden.net/VSCode) available for `ConTeXt`, but wonder if it can of some help, although I'm more inclined to use `vim`/`SublimeText`?

**Comment by valentjn** [comment]
Fix released in 15.2.0. The support is not as good as for L<sup>A</sup>T<sub>E</sub>X, but it should suffice for now.
