### ISSUE TITLE
LaTeX parser incorrectly recognizes names with diactrics

### ISSUE THREAD

**Issue by nightuser** [valentjn/languagetool-languageserver#130]
**Describe the bug**
If a name have several diactrics, only the part of it is recognized as a word.

**Steps to reproduce**

1. Have a name Žák in the text, written as `{\v Z}{\'a}k`.
2. ltex parses it as “ák” and produces the error “'ák': Possible spelling mistake found.”

**Expected behavior**
It should be recognized correctly.

**LTeX configuration**
Default.

**Version information**
List here the version information of the relevant software.

- Operating system: ArchLinux
- ltex-ls: 15.2
- Java: openjdk 17.0.1

**Comment by valentjn** [comment]
It works when using `\v{Z}\'{a}k`, or when using Unicode (LuaL<sup>A</sup>T<sub>E</sub>X).

I'll have to see whether this will be fixed. Formally, `{ ... }` is opening a new group, which could contain anything, really (not just a single letter), and it's pretty plain-T<sub>E</sub>X-ish.
