### ISSUE TITLE
generic language code "es" gives spelling corrections

### ISSUE THREAD

**Issue by rdiaz02** [valentjn/languagetool-languageserver#136]
**Describe the bug**
According to https://valentjn.github.io/ltex/settings.html#ltexlanguage

"Use a specific variant like "en-US" or "de-DE" instead of the generic language code like "en" or "de" to obtain spelling corrections (in addition to grammar corrections)."

This does not seem to apply to Spanish: the generic "es" (there is also a specific variant "es-AR") gives spelling corrections. 

**Steps to reproduce**

Create a configuration file with 

1. Call the CLI program on any file with, say, both English and Spanish words as
```
echo '{"ltex.language":"es"}' > config; ./ltex-cli --client-configuration=config /home/ramon/tmp/minimal.tex
```
You get output such as

```
/home/ramon/tmp/minimal.tex:10:1: info: 'Cucaracho': Se ha encontrado un posible error ortográfico. [MORFOLOGIK_RULE_ES]
Cucaracho
Use 'Cucaracha'
Use 'Cu caracho'
Use 'Cucara cho'
```

2. Compare that with using `ltex.language = "en"`:
```
echo '{"ltex.language":"en"}' > config; ./ltex-cli --client-configuration=config ~/tmp/minimal.tex

```
No spelling errors reported.

**Expected behavior**
Since both "es" and "es-AR" exist, `ltex.language` set to "es" should not do spelling checks.

I understand, though, that this might be debatable. There is an "es-AR" but no other specific "es" variants (say, "es-ES" for "es" for Spain or "es-MX" for Mexico, etc). 

**Sample document**
```
\documentclass[10pt,letterpaper]{article}

\begin{document}

She go home. And now she goes spellingerrorhome

Hola
Holaaa
Cucaracha
Cucaracho

\end{document}

```

**LTeX configuration**

I am using no other configuration.

**Version information**
- Operating system: Linux (Debian, mix of testing and unstable)
- ltex-ls: 15.2.0
- Java: using the one included in the download: jdk-11.0.12+7 (Download: 
https://github.com/valentjn/ltex-ls/releases/download/15.2.0/ltex-ls-15.2.0-linux-x64.tar.gz).

**Additional context/information**
Note: of course, this also happens if using `ltex-ls` from Emacs with https://github.com/emacs-languagetool/lsp-ltex and doing  `(setq lsp-ltex-language "es")`  (the Emacs LSP process shows spelling errors) vs setting the language to "en" (no spelling errors reported).

**Comment by rdiaz02** [comment]
I think the above is, if I am understanding the documentation correctly, a bug. However, it is simple to have LTeX ignore those rules, as explained in the documentation. For anyone stumbling on this, the following would do (no spell checks for Spanish or US English):

```
echo '{"ltex.disabledRules": {"en-US": ["MORFOLOGIK_RULE_EN_US"], "es": ["MORFOLOGIK_RULE_ES"]}}' > config; ./ltex-cli --client-configuration=config /home/ramon/tmp/minimal.tex
```


(For the sake of completeness: if you are using Emacs' lsp-ltex, https://github.com/emacs-languagetool/lsp-ltex, you can do

```
(setq lsp-ltex-disabled-rules 
              #s(hash-table size 30 data 
                        ("en-US" ["MORFOLOGIK_RULE_EN_US"]
			  "es" ["MORFOLOGIK_RULE_ES"])
			))
```
(that 30 is probably unnecessarily large here; adjust as needed ---https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Hash.html).

**Comment by valentjn** [comment]
From a strict logical point of view, the sentence `Use a specific variant like "en-US" or "de-DE" instead of the generic language code like "en" or "de" to obtain spelling corrections (in addition to grammar corrections).` doesn't imply that there are no spelling corrections if you use a generic language code. It just says that there are spelling corrections if you use a specific variant.

However, as that was the intention behind the sentence, and also what I thought would be true, I'll rephrase that. Setting to confirmed as this seems to cause confusion.
