### ISSUE TITLE
Ignore commented lines for `gitcommit` filetype

### ISSUE THREAD

**Issue by mjlbach** [valentjn/languagetool-languageserver#141]
**Is your feature request related to a problem? Please describe.**

I love ltex-ls, especially when writing git commit messages as it picks up on grammatical mistakes when spell checking that simple spellchecking would miss.

Right now, it appears the server sends diagnostics for the commented lines pre-populated in the commit messages template:
![image](https://user-images.githubusercontent.com/13316262/148273629-776c7f27-3cac-4cf9-a576-b20d74a63a9d.png)

**Describe the solution you'd like**
Ignore the commented lines (or silence diagnostics for them). 

**Describe alternatives you've considered**
This could hypothetically be implemented client side as well, but I thought I would raise the issue :

**Comment by valentjn** [comment]
This was already fixed on `develop` in 1193c9959a.

**Comment by OopsYao** [comment]
Hi, it seem like that the diff output in `gitcommit` file does not get ignored.
![ok](https://github.com/valentjn/ltex-ls/assets/32776639/5e654f0a-5002-420e-a2fd-0d5dfc9ce24c)

According to the [doc of git](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---verbose),
> this diff output doesn’t have its lines prefixed with `#`. 

And normally the diff output goes after the line (not documented):
```
# ------------------------ >8 ------------------------
```

It would be nice if this can be solved.
