### ISSUE TITLE
Ltex do not pick a file as dictionary

### ISSUE THREAD

**Issue by cinghiopinghio** [valentjn/languagetool-languageserver#157]
**Describe the bug**
When defining `dictionary.en-US = ":path/to/file"`, the words in the text file are not added to the word list.

**Steps to reproduce**

test config `test.json`:
```
{
    "dictionary": {
        "en-US": [
            "pluto",
            ":/path/to/test.txt"
        ]
    }
}
```

test dictionary `test.txt`:
```
pippo
```
run the code:
```
echo "This is pippo and pluto." | ltex-cli --client-configuration=test.json -
```

I get the output:
```
-:1:9: info: 'pippo': Possible spelling mistake found. [MORFOLOGIK_RULE_EN_US]
This is *pippo* and pluto.
        Use 'hippo'
```

**Expected behavior**
One would expect that the words listed in `test.txt` are not found as errors.

**LTeX configuration**
see above

**LTeX LS log**
see above

**Version information**

Linux (Archlinux).

```
{
  "ltex-ls": "15.2.0",
  "java": "11.0.12"
}
```

**Comment by valentjn** [comment]
External files are not supported by ltex-ls, only by vscode-ltex/coc-ltex ([&ldquo;Setting Scopes & Files&rdquo;](https://valentjn.github.io/ltex/vscode-ltex/setting-scopes-files.html) is under &ldquo;vscode-ltex / coc-ltex&rdquo;, not &ldquo;LT<sub>E</sub>X LS&rdquo;).

**Comment by cinghiopinghio** [comment]
Thanks for the quick reply.

Indeed you are right. I get confused by the fact that this configuration appears also in [the global configuration](https://valentjn.github.io/ltex/settings.html#ltexdictionary).
There is no mention to the fact that it may not work in `ltex-ls`.

**Comment by valentjn** [comment]
There is a striped bar to the left of the text&mdash;when you hover it, it says that it's client-specific.

I guess it's a good idea to state this more prominently somewhere at the top.

**Comment by cinghiopinghio** [comment]
I see, thanks anyway.
