### ISSUE TITLE
Quarto compatibility

### ISSUE THREAD

**Issue by RegisGourdel** [valentjn/languagetool-languageserver#180]
Hi, first thanks a lot for your work on this extension, it is the one thing that allows my VS code to still be more competitive than other solutions for LaTeX.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Quarto documents have a specific file extension, *qmd*, meaning that it's not natively treated by LTEX at the moment. But the compatibility would make a lot of sense, and the parsing would probably be almost the same as for markdown files.

**Describe alternatives you've considered**
Two non-optimal solutions:
1. Exporting the file tex file (in the process of exporting to pdf), browsing through the tex file with LTeX to find mistakes, and correcting in the original qmd file.
2. Telling VS code to consider the original file as markdown, but then it has some syntax issues in particular with the yaml, and it needs to be changed back.

**Additional context**
So, [Quarto](https://quarto.org/) is a recent pandoc-based solution that is very much between markdown and latex in terms of both syntax of capabilities, with easy conversion to both.
It's gaining popularity and I'm replacing some of my tex documents by this because it runs very nicely.

**Comment by sondalex** [comment]
Hi, I have proposed a feature a draft PR few months ago  #172 . I put this message here for anyone who would like to build on this draft and eventually enable [flexmark-java extension] (https://github.com/vsch/flexmark-java)  in order to take care of pandoc's markdown special cases.

**Comment by valentjn** [comment]
Fixed via #172, thanks for the PR.
