### ISSUE TITLE
asciidoc support

### ISSUE THREAD

**Issue by languitar** [valentjn/languagetool-languageserver#185]
Asciidoc is another option for a lightweight markup language that somehow sits in between restructured text and markdown. Having support for asciidoc in ltex would be a nice addition as asciidoc is often used for longer texts that would benefit from good language checking.

**Comment by valentjn** [comment]
Closing as duplicate in favor of transferred issue #220 (and as a duplicate of #148).

**Comment by valentjn** [comment]
Duplicate of #220
