### ISSUE TITLE
Building from source for operating systems that are not mainstream linux.

### ISSUE THREAD

**Issue by anoduck** [valentjn/languagetool-languageserver#186]
**Is your feature request related to a problem? Please describe.**
I was unable to discover information on compiling this lsp from source. I run OpenBSD, therefore prebuilt binaries for Linux will not run on my system. 

**Describe the solution you'd like**
Either direct me please to where I can find information on compiling the lsp from source, or provide information describing building from source, or add an OpenBSD binary to the release sets.

**Describe alternatives you've considered**
The only other alternative is simply not use an lsp.

**Additional context**
nope

**Comment by valentjn** [comment]
[Right now, OpenBSD is not officially supported by LT<sub>E</sub>X LS.](https://valentjn.github.io/ltex/ltex-ls/installation.html#requirements)

LT<sub>E</sub>X LS itself is written in Kotlin, which runs on JVM. Therefore, if you have Java installed on your system, you can run the language server theoretically by downloading the [platform-independent release](https://github.com/valentjn/ltex-ls/releases/download/15.2.0/ltex-ls-15.2.0.tar.gz), see [installation docs](https://valentjn.github.io/ltex/ltex-ls/installation.html#installation).

There is a catch though. I think LanguageTool, the backend behind LT<sub>E</sub>X LS contains some binary dependencies. If your OS is not supported by these dependencies, then you're out of luck. You have to try it, though.

**Comment by anoduck** [comment]
@valentjn Appreciate it. I have had LanguageTool installed before, so it might work. I will give it a whirl. Thanks.
