### ISSUE TITLE
\subimport checks grammar in filenames

### ISSUE THREAD

**Issue by mfbehrens** [valentjn/languagetool-languageserver#207]
**Describe the bug**
```\subimport*{../}{sitzung_daten.tex}```
and
```\subimport{../}{sitzung_daten.tex}```
throws an error that two dots are not allowed

**Comment by valentjn** [comment]
Fixed for `\import` and `\subimport`. The starred variants of those macros are the same as the non-starred macros since version 6.0 of the import package, but they are ignored now nevertheless.
