### ISSUE TITLE
babel naustrian is not detected as austrian german

### ISSUE THREAD

**Issue by 456Xander** [valentjn/languagetool-languageserver#213]
**Describe the bug**
When using LaTeX and babel, the language should be detected automatically.
Using babel with ngerman, the language is correctly detected as de-DE.
However, when writing documents in austrian German (babel naustrian), the language gets wrongly detected as en-US.
The detected language should be de-AT.

**Steps to reproduce**
Create a Latex document and use 

    \usepackage[naustrian]{babel}

**Expected behavior**
Language gets detected as de-AT.

**Sample document**

<details>

```latex
\usepackage[naustrian]{babel}
\documentclass[a4paper]{scrartcl}
\begin{document}
Das ist ein korrekter Satz.
\end{document}
```

</details>

**LTeX configuration**

Using ltex with neovim and nvim-lspconfig. Configuration is provided by Spacevim.

**LTeX LS log**
Paste the log (output) of LTeX LS here:

<details>

```
[ERROR][2023-01-06 12:27:53] .../vim/lsp/rpc.lua:733	"rpc"	"ltex-ls"	"stderr"	"Jan 06, 2023 12:27:53 PM org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked\nFINE: Checking the following text in language 'en-US' via LanguageTool: \" Das ist ein korrekter Satz. \"\n"
[ERROR][2023-01-06 12:27:53] .../vim/lsp/rpc.lua:733	"rpc"	"ltex-ls"	"stderr"	"Jan 06, 2023 12:27:53 PM org.bsplines.ltexls.server.DocumentChecker checkAnnotatedTextFragment\nFINE: Obtained 5 rule matches\n"
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Arch Linux
- ltex-ls: 15.2.0-1
- Java: 17.0.5

**Comment by valentjn** [comment]
Fixed in 1a903cdb8e63f74616a1fc8db4c9821a2ed73644.
