### ISSUE TITLE
Use "nightly" for the nightly version string

### ISSUE THREAD

**Issue by BlackEdder** [valentjn/languagetool-languageserver#226]
**Is your feature request related to a problem? Please describe.**
I would like to use the ltex-ls nightly, because it recently added rmarkdown support. I could do this by hand, but ideally I'd use a tool (mason) to install the nightly. The problem though is that the custom name of the nightly makes it hard to automatically download and install

**Describe the solution you'd like**
Instead of using the custom version tag, just use nightly as version. This would make it so that the download url would be `https://github.com/valentjn/ltex-ls/releases/download/nightly/ltex-ls-nightly.tar.gz`, which is inline with the regular version naming scheme: `https://github.com/valentjn/ltex-ls/releases/download/<version>/ltex-ls-<version>.tar.gz`

**Comment by valentjn** [comment]
I'm not convinced of this proposal. Using a distinctive, SemVer-compliant version avoids confusion when third parties distribute nightly builds of LT<sub>E</sub>X LS, especially now that there has been no regular release for some time. Using the same name for multiple pre-releases makes it hard to find out on which commit an archive stems from.

Regarding scripting the download of nightly releases: [Using GitHub API, it is not hard to list the releases, find the nightly release, and grab the download URL in question.](https://docs.github.com/en/rest/releases/releases#list-releases)
