### ISSUE TITLE
Incompatible with nvim notif

### ISSUE THREAD

**Issue by illegitimate-egg** [valentjn/languagetool-languageserver#237]
**Describe the bug**
You receive a barrage of notifications when using nvim notif

**Steps to reproduce**

Install nvim notif with the recommended configuration

**Expected behavior**
One notification when changing modes

**LTeX configuration**
Please paste all configuration settings starting with `ltex.` from your `settings.json`. You can help us by temporarily removing some irrelevant settings from your `settings.json` and see if the bug still occurs.

<details>

I don't have anything in my settings.json

</details>

**LTeX LS log**
Paste the log (output) of LTeX LS here:

<details>

```
Cannot work out how to get the log
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Ubuntu WSL (Custom Kernel) 22.04 with snap removed
- ltex-ls: 15.2.0
- Java: OpenJDK 19.0.2 2023-01-17

**Comment by valentjn** [comment]
I don't know what &ldquo;nvim notif&rdquo; is. The listed info in the steps to reproduce (&ldquo;Install nvim notif with the recommended configuration&rdquo;) are not sufficient for me to reproduce this. Maybe the problem is in nvim notif.

**Comment by illegitimate-egg** [comment]
Ah, I made a typo. It should have been nvim-notify. The solution was just to check if the LSP server is ltex and if it is do nothing
