### ISSUE TITLE
Is it possible to use regular expressions or wildcards in `ltex.latex.commands`?

### ISSUE THREAD

**Issue by gabrielbdsantos** [valentjn/languagetool-languageserver#252]
First of all, thanks for this awesome project. It is really a lifesaver!

So, normally, I define some new commands for the glossaries package, which can vary from project to project. Nonetheless, all of them follow the same pattern. For example, something like `\glsMyCMD*`.

Is there a way of making LTeX aware of this pattern? I mean, something like regular expressions or wildcards when setting `ltex.latex.commands`.

**Comment by thunderbird-1990** [comment]
If I understood it correctly, this [issue](https://github.com/valentjn/vscode-ltex/issues/226) of vscode-ltex suggests that this feature won't be added.

**Comment by gabrielbdsantos** [comment]
Yeah. You are right. Thanks for pointing out this issue.
