### ISSUE TITLE
Switch language for file in neovim

### ISSUE THREAD

**Issue by pinpox** [valentjn/languagetool-languageserver#256]
I often write in different languages. Is there a way to switch the current language in neovim? I couldn't find any information on that except for setting the language permanently in the configuration.

Is ther any way to create a keybind to switch the language or to change it via a command?

**Comment by muniter** [comment]
```lua
vim.api.nvim_create_user_command("LtexLangChangeLanguage", function(data)
    local language = data.fargs[1]
    local bufnr = vim.api.nvim_get_current_buf()
    local client = vim.lsp.get_active_clients({ bufnr = bufnr, name = 'ltex' })
    if #client == 0 then
        vim.notify("No ltex client attached")
    else
        client = client[1]
        client.config.settings = {
            ltex = {
                language = language
            }
        }
        client.notify('workspace/didChangeConfiguration', client.config.settings)
        vim.notify("Language changed to " .. language)
    end
end, {
    nargs = 1,
    force = true,
})
```

Then in a buffer where it's being used: `:LtexLangChangeLanguages en`

**Comment by pinpox** [comment]
> ```lua
> vim.api.nvim_create_user_command("LtexLangChangeLanguage", function(data)
>     local language = data.fargs[1]
>     local bufnr = vim.api.nvim_get_current_buf()
>     local client = vim.lsp.get_active_clients({ bufnr = bufnr, name = 'ltex' })
>     if #client == 0 then
>         vim.notify("No ltex client attached")
>     else
>         client = client[1]
>         client.config.settings = {
>             ltex = {
>                 language = language
>             }
>         }
>         client.notify('workspace/didChangeConfiguration', client.config.settings)
>         vim.notify("Language changed to " .. language)
>     end
> end, {
>     nargs = 1,
>     force = true,
> })
> ```
> 
> Then in a buffer where it's being used: `:LtexLangChangeLanguages en`

Wow, that's perfect. Thank you!
