### ISSUE TITLE
Use serverInitiatedProgress instead of custom notifications

### ISSUE THREAD

**Issue by LDAP** [valentjn/languagetool-languageserver#34]
**Is your feature request related to a problem? Please describe.**
ltex-ls is using custom notifications for progress reporting.

**Describe the solution you'd like**
Replace it with the standard [server initiated progress scheme](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#serverInitiatedProgress) of the LSP specification.
See https://github.com/microsoft/pyright/issues/1268 for a analog discussion

`ltex/progress`, with progress 0.0 --> `window/workDoneProgress/create` + `$/progress` with kind begin
`ltex/progress`, with progress 1.0 --> `$/progress with kind end`

**Additional context**
Simplifies integration with non vscode-ltex clients.

**Comment by valentjn** [comment]
This is already done, just haven't pushed yet.

**Comment by LDAP** [comment]
I would like to reopen this issue (but I can't due to GitHub permissions).

I tested the 9.0.0 alpha and it seams that the specification for [serverInitiatedProgress](https://microsoft.github.io/language-server-protocol/specification#serverInitiatedProgress) is not met.

I think currently the server is implementing [clientInitiatedProgress](https://microsoft.github.io/language-server-protocol/specification#clientInitiatedProgress) insted. But in this case the progress should be initiated by LTEX-LS.

The specification requires the server to
- Initiate progress reporting using the window/workDoneProgress/create request.
- Report progress using the generic $/progress notification.

Additionaly, 
- the `title` parameter should only briefly inform about the kind of operation being performed. (e.g. Checking document).
- The uri of the file should instead be part of the `message` parameter.
- see [here](https://microsoft.github.io/language-server-protocol/specification#workDoneProgressBegin)

**Comment by valentjn** [comment]
The server didn't use client-initiated progress as the tokens used by the server notifications are not introduced by the client before the server notifications. Just the `window/workDoneProgress/create` request was missing for server-initiated progress. This is fixed now, as well as the progress title.

**Comment by LDAP** [comment]
Does work now with the LSP client for Sublime Text too.

**Comment by valentjn** [comment]
Fix released in 9.0.0.
