### ISSUE TITLE
Are there any thoughts on creating a Vim/Neovim plugin as well ?

### ISSUE THREAD

**Issue by searleser97** [valentjn/languagetool-languageserver#51]
Similar to [vscode-ltex](https://github.com/valentjn/vscode-ltex) but for Vim/Neovim

**Comment by valentjn** [comment]
Thanks for the suggestion. Unfortunately, I don't use Vim at all. I think it's best if such a plugin is created by someone who uses Vim for their everyday work (like I do with VS Code).

As LT<sub>E</sub>X is basically a front-end for LanguageTool, you can try one of the existing LanguageTool plugins such as [rhysd/vim-grammarous](https://github.com/rhysd/vim-grammarous) or [dpelle/vim-LanguageTool](https://github.com/dpelle/vim-LanguageTool) (see also [this list at dev.languagetool.org](https://dev.languagetool.org/software-that-supports-languagetool-as-a-plug-in-or-add-on)). I don't know if they support L<sup>A</sup>T<sub>E</sub>X and Markdown, though.

Depending on how well Vim supports the Language Server Protocol (LSP), it might not be too hard to implement a client that uses ltex-ls. After all, most of vscode-ltex's code is boilerplate for downloading the dependencies Java and LanguageTool. However, such a plugin would have to be maintained as well (bugs, questions, etc.), and therefore I think such a plugin is a job for persons familiar with Vim.

**Comment by valentjn** [comment]
I guess it's fairly easy with [vim-lsp](https://github.com/prabirshrestha/vim-lsp). But I don't know that scripting language, so I can't help. If someone creates a language client, I'll be happy to add it to the list in the readme.

**Comment by valentjn** [comment]
In #68, someone managed to get LT<sub>E</sub>X to work with Neovim using the built-in LSP client.

**Comment by valentjn** [comment]
LT<sub>E</sub>X is now officially published as a [coc.nvim](https://github.com/neoclide/coc.nvim) extension named [coc-ltex](https://www.npmjs.com/package/coc-ltex). Just install `coc.nvim`, run `:CocInstall coc-ltex`, and enjoy LT<sub>E</sub>X.
