### ISSUE TITLE
CLI parameters unresponsive

### ISSUE THREAD

**Issue by lbiaggi** [valentjn/languagetool-languageserver#67]
**Describe the bug**
CLI options don't seem to work except for --version, even -V doesn't seem to work

**Steps to reproduce**

1 - try to execute the supplied ltex-ls script with -V or any option doesn't change anything.

**Expected behavior**
work as described

**Version information**
List here the version information of the relevant software.

- Operating system: Linux, Manjaro
- ltex-ls: 11.00
- Java: openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)

**Additional context/information**
You can add any other context or information about the problem here.

**Comment by valentjn** [comment]
Just tested it, cannot reproduce. You probably called the wrong executable, or you have another version on your `PATH`.

Edit: The issue description says you're using version &ldquo;11.00&rdquo; of ltex-ls. If you mean 11.0.0, then that's the wrong version. The CLI options were added in 12.0.0.
