### ISSUE TITLE
Non-server command-line interface (CLI)

### ISSUE THREAD

**Issue by hdorgeval** [valentjn/languagetool-languageserver#71]
Hi, I am using your extension to manually correct markdown files and it works great!

I would like to know if there is a way to write a script inside [my visual studio project](https://github.com/hdorgeval/le-livre-des-rois) (nodejs + typescript), that could tell for any given markdown filepath if there is an error or not in the file.

Thanks for your response.

---

*Note: Originally posted as issue 317 &ldquo;How to use this extension programmatically?&rdquo; at [valentjn/vscode-ltex](https://github.com/valentjn/vscode-ltex).*

**Comment by valentjn** [comment]
This is now implemented via `--input-documents`. I opted for a human-readable output, which may be processed by scripts at the same time. The exit code indicates whether no grammar/spelling errors were found (exit code 0), or at least one error (exit code 3).

**Comment by hdorgeval** [comment]
Hi @valentjn , thank you so much for integrating this new feature 👍 . 

I will test it and I will give you some feedback as soon as it is published.

Regards

**Comment by valentjn** [comment]
FWIW, `develop`, which includes this feature, is already published as [pre-release on a nightly basis](https://github.com/valentjn/ltex-ls/releases). The same holds for vscode-ltex, which should be irrelevant in this case.

**Comment by valentjn** [comment]
Feature released in 13.0.0.
